# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dcf9578a2653321582a3bd681597ff3224058243d8a92ea0df7c05f5b5ffe27506214712947aff8ec0cb0a8cf95cc2fee999ae81360a7210a2c46c083ed8c2c7

test:
  secret_key_base: 4fcde0862cbf192c50beb6a28f5d8c5162f5187331c5c372af92b6124cbff7764c823098ef3b30c35ba663e6071cc9bdd7cde7f4a0ccb1b896628007d13bfff2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
